apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextflow
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextflow-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/status", "pods/log", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextflow-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextflow-role
subjects:
- kind: ServiceAccount
  name: nextflow
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: nextflow-launcher
  namespace: default
  labels:
      nextflow.io/app: nextflow
      role: launcher
spec:
  serviceAccountName: nextflow
  restartPolicy: Never
  initContainers:
  - name: git-clone
    image: alpine/git
    command:
    - git
    - clone
    - https://github.com/sktrinh12/nextflow-wgs-variant-call.git
    - /workspace/project
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  containers:
  - name: nextflow
    image: nextflow/nextflow:25.10.2
    command: ["bash"]
    stdin: true
    tty: true
    workingDir: /workspace
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: nextflow-pvc
